apiVersion: apps/v1
kind: Deployment
metadata:
  name: geojson-ingestion
  namespace: default
  labels:
    app: geojson-ingestion
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geojson-ingestion
  template:
    metadata:
      labels:
        app: geojson-ingestion
        version: v1.0.0
    spec:
      containers:
      - name: geojson-ingestion
        image: 826331272066.dkr.ecr.us-east-1.amazonaws.com/silver-saas-geojson-ingestion:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: geojson-db-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: geojson-db-secret
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: geojson-db-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: geojson-db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: geojson-db-secret
              key: DB_PASSWORD
        - name: DB_SSLMODE
          valueFrom:
            secretKeyRef:
              name: geojson-db-secret
              key: DB_SSLMODE
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
