apiVersion: v1
kind: Secret
metadata:
  name: geojson-db-secret
  namespace: default
  labels:
    app: geojson-ingestion
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded values
  # To encode: echo -n "your-password" | base64
  DB_USER: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cG9zdGdyZXM=  # postgres (default)
  DB_HOST: c2lsdmVyLXNhYXMtcG9zdGdyZXMuY3NidWVrd2lvaW1rLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==  # silver-saas-postgres.csbuekwioimk.us-east-1.rds.amazonaws.com
  DB_NAME: Z2VvanNvbl9kYg==  # geojson_db
  DB_PORT: NTQzMg==  # 5432
  DB_SSLMODE: cHJlZmVy  # prefer
