name: CI/CD Deploy to EKS

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: silver-saas-cluster
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build, Tag, and Push Docker image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/hpa.yaml
        kubectl apply -f k8s/secret.yaml
        
    - name: Initialize Database (if needed)
      run: |
        # Check if database needs initialization
        if ! kubectl exec -it $(kubectl get pods -l app=geojson-ingestion -o jsonpath='{.items[0].metadata.name}') -- python3 -c "import psycopg2; import os; conn = psycopg2.connect(host=os.getenv('DB_HOST'), database=os.getenv('DB_NAME'), user=os.getenv('DB_USER'), password=os.getenv('DB_PASSWORD'), port=os.getenv('DB_PORT'), sslmode=os.getenv('DB_SSLMODE')); cursor = conn.cursor(); cursor.execute('SELECT COUNT(*) FROM information_schema.tables WHERE table_name = \'geo_features\';'); count = cursor.fetchone()[0]; print(count); conn.close()" | grep -q "0"; then
          echo "Database already initialized, skipping init-db job"
        else
          echo "Initializing database with init-db job"
          kubectl apply -f k8s/init-db-job.yaml
          kubectl wait --for=condition=complete job/init-db --timeout=300s
        fi

    - name: Wait for deployment
      run: |
        kubectl rollout status deployment/geojson-ingestion --timeout=300s

    - name: Get service info
      run: |
        echo "🚀 Deployment complete!"
        echo "Service URL:"
        kubectl get service geojson-ingestion-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
        echo ""
        echo "Pod status:"
        kubectl get pods -l app=geojson-ingestion
